# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: ReDeployAgentPool


steps:
- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: 'ReDeployPip1'
    backendAzureRmOverrideSubscriptionID: '$(SubID)'
    backendAzureRmResourceGroupName: '$(SARG)'
    backendAzureRmStorageAccountName: '$(SAName)'
    backendAzureRmContainerName: '$(CName)'
    backendAzureRmKey: '$(SAKey)'

- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'ReDeployPip1'
    environmentAzureRmOverrideSubscriptionID: '$(SubID)'

- task: TerraformTask@5
  displayName: terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'ReDeployPip1'
    environmentAzureRmOverrideSubscriptionID: '$(SubID)'